1~6장까지 사이킷런에 포함된  
다양한 머신러닝 알고리즘을 배움  

8장은 합성곱 신경망에 대해 자세히 배우고  
7~9장은 텐서플로를 사용한 딥러닝 알고리즘을 다룹니다.
|제목|굵은글자|이탤릭체(기울이기)|<코드형식>|글자를 링크로 만들기|이미지 추가|들여 쓴 블록을 추가|번호 매기기 목록을 추가|글머리 기호목록을 추가|가로줄을 추가| 미리 보기 창의 위치를 가로 또는 세로로 바꿈

In [ ]:
seconds_in_a_day = 24 * 60 * 60
seconds_in_a_day

86400

노트북  
코랩은 구글이 대화식 프로그래밍 환경인 주피터를 커스터마이징 한 것

In [ ]:
print("Hello World")

Hello World

In [ ]:
import pandas as pd
df = pd.read_csv('Fish.csv')

In [ ]:
df

    Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [ ]:
if fish_length >= 30:
  print("도미")